---
title: "Compile known farm locations and farms to add data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in all known farms data and bind together for one file. 

```{r}
bivalve_farms <- read_csv(here("marine/bivalve/bivalve_farms/output/all_known_bivalve_farms_final.csv"))
  
crustacean_farms <- read_csv(here("marine/crustaceans/crustaceans_farms/output/all_known_crustaceans_farms_final.csv")) ## there are none
  
finfish_farms <-  read_csv(here("marine/marine_fish_general/finfish_farms/output/all_known_finfish_farms_final.csv"))
  
shrimp_farms <-  read_csv(here("marine/shrimp/shrimp_farms/output/all_known_shrimp_farms_final.csv"))
  
tuna_farms <-  read_csv(here("marine/tuna/tuna_farms/output/all_known_tuna_farms_final.csv"))
  
salmon_farms <-  read_csv(here("marine/salmon/salmon_farms/output/all_known_salmon_farms_final.csv")) %>%
  dplyr::select(-subregion)

## bind together

all_farms <- rbind(bivalve_farms, finfish_farms, shrimp_farms, tuna_farms, salmon_farms, crustacean_farms)
  
## now write to our output folder
write.csv(all_farms, here("marine/output/all_marine_farms.csv"), row.names = FALSE)
  
unique(all_farms$type)

```

Read in the points to add data and bind together for one file. 

```{r}
bivalve_farms_add <- read_csv(here("marine/bivalve/bivalve_farms/output/bivalve_points_to_add_final.csv"))
  
crustacean_farms_add <- read_csv(here("marine/crustaceans/crustaceans_farms/output/crustaceans_points_to_add_final.csv")) 
  
finfish_farms_add <-  read_csv(here("marine/marine_fish_general/finfish_farms/output/marine_fish_general_points_to_add_final.csv"))
  
shrimp_farms_add <-  read_csv(here("marine/shrimp/shrimp_farms/output/shrimp_points_to_add_final.csv"))
  
tuna_farms_add<-  read_csv(here("marine/tuna/tuna_farms/output/tuna_points_to_add_final.csv"))
  
salmon_farms_add <-  read_csv(here("marine/salmon/salmon_farms/output/salmon_points_to_add_final.csv"))

all_point_additions <- rbind(bivalve_farms_add, crustacean_farms_add, finfish_farms_add, shrimp_farms_add, tuna_farms_add, salmon_farms_add)

## write to our output folder
write.csv(all_point_additions, here("marine/output/all_points_to_add.csv"), row.names = FALSE)

str(all_point_additions)
summary(all_point_additions)
unique(all_point_additions$type)
```

```{r}
countries_1 <- data.frame(iso3c = unique(all_farms$iso3c))

countries_2 <- data.frame(iso3c = unique(all_point_additions$iso3c))

all_countries <- rbind(countries_1, countries_2)

length(unique(all_countries$iso3c)) # 73 total countries mapped 
```


