---
title: "get number of farms"
author: "Gordon Blasco"
date: "3/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(janitor)
library(tidymodels)
library(WDI)
library(countrycode)


continent_info <- read_csv('data/CL_FI_COUNTRY_GROUPS.csv') %>% 
  janitor::clean_names() %>% 
  select(iso3_code, geo_region_group, continent_group, eco_class_group)

raw <- read_csv("/home/blasco/github/aquaculture_mapping/marine/data/n_farms_production_data.csv") %>% 
  left_join(aq_info, by = c('iso3c' = 'iso3_code'))




```









































```{r}
ready <- raw %>% 
  mutate(iso2c = purrr::map_chr(.x = iso3c, 
                           ~countrycode(sourcevar = .x, 
                                        origin = "iso3c", 
                                        destination = "iso2c")))

# helper functions
test <- possibly(countryname, NA_character_)


# pulls most recent information from the WDI call
get_most_recent_variable <- function(data){
 data %>% 
    filter(!is.na()) %>% 
    arrange(-year) %>% 
    slice(., 1) %>% 
    pull()
  
}

poss <- possibly(get_most_recent_variable, NA_real_)



```


pull WDI stats for each country
```{r}


wdi_info <- ready %>% 
  distinct(iso2c) %>% 
  mutate(wdi_data_pull = purrr::map(.x = iso2c, 
                               ~possibly(
                                 WDI(indicator= c("gdp_per_capita" = "NY.GDP.PCAP.KD",
                                                 "population" = "SP.POP.TOTL",
                                                 "literacy_rate" = "LO.PIAAC.LIT",
                                                 "life_expectancy"="SP.DYN.LE00.IN",
                                                 "GNI_PPP_per_cap" = "NY.GNP.PCAP.PP.KD",
                                                 "industrial_prod" = "IPTOTNSKD",
                                                 "greenhouse_gas_kt" = "EN.ATM.GHGT.KT.CE"),
                                    country=.x, 
                                    start=2010, end=2017), NA))
  )





wdi_test <- wdi_info %>% 
  mutate(
    
    gdp_final = map2_dbl(.x = GDP,
                         .y = c("gdp_per_capita", "population"),
                         ~poss(data = .x,
                               variable_name = .y))
    
  ) 

```

