---
title: "Data checking"
author: "Gage Clawson (UCSB, NCEAS, OHI)"
date: "03/06/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}

library(here)
library(dplyr)
library(sf)
library(raster)
library(mapview)
library(janitor)

source(here("_spatial/template_raster.R"))

path <- "/home/shares/food-systems/Food_footprint/_raw_data/Aquaculture_locations"

```


# Global regions

```{r}

# this file includes ocean regions:
gadm <- raster("/home/shares/food-systems/Food_footprint/_raw_data/Country_regions/gadm36mol_pyfill_10km.tif")

gadm_latlon <- raster::projectRaster(gadm, food_raster, method="ngb", over=TRUE)
plot(gadm_latlon)

gadm_codes <- read.csv("/home/shares/food-systems/Food_footprint/_raw_data/Country_regions/gadm_reg_codes.csv") %>% 
  mutate(reg_id = as.numeric(reg_id))

```

# read in points and converted to spatial dataframe
```{r}

data <- read_csv("marine/output/all_marine_farms.csv") %>% 
  st_as_sf(., 
           coords = c("lon", "lat"),
           crs = crs(food_raster), 
           agr = "constant") 

all_farms <- list.files("data/temp_data/temp_marine_final", pattern = "rds$", full.names = TRUE) %>% 
  map_df(., readRDS) %>% 
  rename(iso3c = iso3) %>% 
  mutate(source = "modeled") %>% 
  rbind(data %>% mutate(source = "real"))

sources_spreadsheet <- read_csv("analysis/data/mariculture_mapping_sources.csv") %>%
  clean_names() %>%
    mutate(type = case_when(species == "Salmonids" ~ "salmon",
                          species == "Unfed or algae fed shellfish" ~ "bivalve",
                          species == "Shrimp" ~ "shrimp", 
                          species == "Tuna" ~ "tuna", 
                          species == "General Marine Fish" ~ "marine_fish_general", 
                          species == "Crustaceans" ~ "crustaceans"))

all_farms_sources <- all_farms %>%
  left_join(sources_spreadsheet, by = c("iso3c", "type"))


by_type <- all_farms %>%
  group_by(type) %>%
  summarise(n()) %>%
  st_drop_geometry()


by_country_type <- all_farms %>%
  st_drop_geometry() %>%
  group_by(iso3c, type) %>%
  summarise(n_obs = n()) %>%
  left_join(sources_spreadsheet, by = c("iso3c", "type")) %>%
  dplyr::select(iso3c, type, n_obs, number_of_total_farms) %>%
  mutate(difference = n_obs - number_of_total_farms)


canada_salmon <- all_farms_sources %>%
  dplyr::filter(iso3c == "CAN", 
                type == "salmon")

mapview(canada_salmon)
```