---
title: "Prep ASC data"
author: "Gage Clawson (USCB, NCEAS, OHI)"
output: html_document
editor_options: 
  chunk_output_type: console
---

Prep the aquaculture stewardship data and save as a shp to use for the different species groups.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(data.table)
library(countrycode)
library(here)
library(stringr)
library(sf)
library(mapview)

path <- "/home/shares/food-systems/Food_footprint/_raw_data"
source(here('marine/salmon/salmon_farm/R/fao_mar_clean.R')) # functions specific to mariculture dealing with compound countries
source('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2019/gh-pages/workflow/R/fao_fxn.R') # function for cleaning FAO files
source(here('workflow/common.R'))
```


```{r}
fao <- read.csv(here("data/fao_aquaculture_clean.csv")) %>%
  filter(environment %in% c("Marine", "Brackishwater"))

species_list <- read.csv(here("marine/STEP1_species_groups/int/marine_groups.csv"))

fao_all <- species_list %>%
  # filter(species %in% shrimp_list) %>%  
  filter(!is.na(value)) %>%
  arrange(-value, country) %>% 
  filter(value>=500) %>%  # countries with less do not appear to be stable producers at this point
  # dplyr::filter(aq_group == "bivalves") %>%
  # dplyr::filter(year == 2017) # countries with less do not appear to be stable producers at this point
  group_by(country, iso3c, aq_group, year) %>%
  summarize(fao_tonnes_production = sum(value)) %>%
  arrange(country, iso3c, year) %>%
  dplyr::filter(year == 2017)
```

```{r}
ASC_data <- read_csv(file.path(here::here("data/ASC_farms.csv"))) ## downloaded from ASC website

unique(fao_all$aq_group)
# [1] "marine_fish_general" "bivalves"            "salmonids"           "shrimps_prawns"     
# [5] "tuna"                "crustaceans"  

unique(ASC_data$species__c)

unique(ASC_data$farm_species)


unique(ASC_data$cert_country)

ASC_classified <- ASC_data %>%
  dplyr::filter(species__c %notin% c("Freshwater Trout", "Pangasius", "Seaweed (Algae)", "Tilapia")) %>%
  mutate(aq_group = case_when(
    species__c %in% c("Shrimp") ~ "shrimps_prawns",
    species__c %in% c("Abalone", "Bivalve") ~ "bivalves",
    species__c %in% c("Salmon") ~ "salmonids",
    species__c %in% c("Seabass, Seabream and Meagre", "Seriola and Cobia", "Tropical Marine Finfish") ~ "marine_fish_general"
  )) 

## Now we need to make the ASC data into an sf
ASC_all_sf <- ASC_classified %>%
  mutate(geometry = str_replace_all(geom, "POINT|[()]", "")) %>%
  mutate(geometry = trimws(geometry)) %>%
  mutate(x= as.numeric(gsub(" .*$", "", geometry))) %>%
  dplyr::filter(!is.na(geom)) %>%
  mutate(y = as.numeric(sub("^\\S+\\s+", '', geometry))) %>%
  dplyr::select(-geometry, -geom, -X10, -X11, -X12, -X13, -X14)  %>%
  st_as_sf(coords = c("x", "y"), crs = 4326)

mapview(ASC_all_sf$geometry)

## now we need to write as a shapefile 
# st_write(ASC_all_sf, "/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/aquaculture/marine/ASC_all_sf.shp", overwrite = TRUE)

st_write(ASC_all_sf, "/home/shares/food-systems/Food_footprint/_raw_data/Aquaculture_locations/ASC_data/ASC_all_sf.shp", overwrite = TRUE)
```